services:
  web:
    build: .
    env_file:
      - .env
    command: bash -c "alembic upgrade head && python main.py"
    container_name: "web"
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    restart: always

  db:
    image: "postgres"
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
